### ISSUE TITLE
unable to compile with SDK validator, validation errors

### ISSUE THREAD

**Issue by JoeJGit** [GPUOpen-LibrariesAndSDKs/VkMBCNT#1]
Your project works fine, but i can't use the extensions in my own.

The shader compiles only with the glslangValidator.exe that comes with this example, but not with any from the LunarG SDK (using 1.0.17 but tried olders as well) - why is this?

Compiled spv still does not work for me. I get those validation errors:

SPIR-V module not valid: Invalid extended instruction import 'SPV_ARB_shader_ballot'
and
Shader requires VkPhysicalDeviceFeatures::shaderInt64 but is not enabled on the device

I can get around the latter by enabling the feature shaderInt64, but i wonder you don't have to do this in your example.

About the former error, i have following extensions enabled (GPU is FuryX):
Device extension: VK_KHR_sampler_mirror_clamp_to_edge
Device extension: VK_KHR_swapchain
Device extension: VK_AMD_rasterization_order
Device extension: VK_AMD_shader_ballot
Device extension: VK_AMD_shader_trinary_minmax
Device extension: VK_AMD_shader_explicit_vertex_parameter
Device extension: VK_AMD_gcn_shader

**Comment by JoeJGit** [comment]
... found a 'bug' on your side: You actually don't enable any extensions.
Unfortunately this does not help me yet...

```
std::vector<const char*> deviceExtensions;

for (auto &ext : extensions) deviceExtensions.push_back (ext.c_str()); // <- bugfix

deviceCreateInfo.ppEnabledExtensionNames = deviceExtensions.data();
deviceCreateInfo.enabledExtensionCount = static_cast<uint32_t> (deviceExtensions.size());
```

**Comment by JoeJGit** [comment]
Ha, the above bugfix replicates the problem in your code too.
After adding the line i get the same validation message:
SPIR-V module not valid: Invalid extended instruction import 'SPV_ARB_shader_ballot'

... i just missed that i need to set a breakpoint in DebugReportCallback to get noticed :D
So the problem is in the validation layers. I suggest you contact them to fix it.

Please comment on the issue about glslangValidator.exe - that's a bit confusing.
It would be nice if the SDK compiler would already support GCN extensions.

**Comment by Anteru** [comment]
The problem here is that the extension process for SPIR-V is still not defined - we're working with Khronos on the details, but it's going to take a while before that is fully formalized and we'll be able to upstream the changes into the `glslangValidator` and the validation layers.

**Comment by JoeJGit** [comment]
I see. No problem in the meantime. Thanks!
