### ISSUE TITLE
spv compiles but crashes

### ISSUE THREAD

**Issue by JoeJGit** [GPUOpen-LibrariesAndSDKs/VkMBCNT#2]
I frequently get this error msg from the validation layers, ignoring it causes a crash:

SPIR-V module not valid: OpExtInst set Id 4294967295 does not reference an OpExtInstImport result Id

I don't have a clue what causes it - it happens when the shader gets a bit more complex.
It also happens if no GCN extension is used or requested.
Unfurtunately that's a show stopper, seems you need to update your glsl->spv compiler.

Side question: What are the function parameters for the other extensions?
After a lot of guessing i'm still unable to get swizzleInvocationsAMD to work.
There is no documentation anywhere.

**Comment by JoeJGit** [comment]
Just found out: The error happens when using sqrt, inversesqrt or length.

**Comment by JoeJGit** [comment]
Some more functions causing the error: abs, floor and ceil.

Another unrelated issue i've got:
Using glslangValidator from actual LunarG SDK i get serious bugs with prefix sum if work group size > 64. Example code:

layout (local_size_x = 128) in;
#define lID gl_LocalInvocationID.x
shared uint _texCount   [257];

for (uint step = 0; step < 8; step++)
{
    uint mask = (1 << step) - 1;
    uint rd_id = ((lID >> step) << (step + 1)) + mask; 
    uint wr_id = rd_id + 1 + (lID & mask);
    uint r = _texCount[rd_id + 1];
    barrier(); memoryBarrierShared(); // paranoia
    _texCount[wr_id + 1] += r;
    barrier(); memoryBarrierShared();
}

Sometimes that codes produces wrong results, causing nice blue screens and stuff.
Errors mostly at index 192 - maybe the barriers don't work.

Using older glslangValidator from 1.0.17 or yours the same code works as expected.

I don't know if it's a driver bug (no NV card at the moment), but more likely it's just an issue with LunarG glslangValidator.
Just to let you know in case you plan an update.


EDIT:
I copied the code from a book and did not notice the wrong order of the barriers.
**memoryBarrierShared(); barrier();**   would have been correct.

Probably this was the reason for the confusion.
At least it helped to spot a true bug in OpenCL which has been fixed meanwhile.

**Comment by jstewart-amd** [comment]
Thanks. Just FYI, @Anteru is currently on vacation, so it will likely be two weeks or so before he is available. I'll check with our other Vulkan gurus to see if they have any spare cycles to comment on this.

**Comment by JoeJGit** [comment]
Thanks. About the prefix sum issue - please ignore this for now, it's not related to any glslangValidator and i still struggle with it. I was able to reproduce it in a OpenCL version (with very different kind of errors), but i was not able to reproduce outside my project. I assume i do something wrong but will let you know if something else turns out...

**Comment by JoeJGit** [comment]
@jstewart-amd Now i'm pretty sure there is a driver bug at least with OpenCL. I made a small test project to reproduce: https://github.com/JoeJGit/OpenCL_Fiji_Bug_Report
I don't know GitHub so i created a zip - please see there for more infos.
(I also posted this on DevGuru forum but i'm not sure if that's the right place)

**Comment by Anteru** [comment]
Quite a bit has changed - on today's driver, you don't have to use the built-in `glslangvalidator` any more, but you need to enable the `shaderInt64` physical device feature. Then everything should work as expected (tested with the LunarG SDK 1.0.33.0). I'll patch the code accordingly.

**Comment by JoeJGit** [comment]
Did a quick test, works without issues. I expect a nice speed up after optimizing my whole project...

Thanks and keep up good work :)
